[package]
name = "vmtests"
version = "0.1.0"
authors = ["James Wang <jameswang9909@hotmail.com>"]

[dependencies]
revm = { path = '..' }
serde_json = "1.0"
etcommon-bigint = "0.2.9"
etcommon-hexutil = "0.2"
lazy_static = "1.1.0"
